//! Export API for 3D formats

use axum::{
    extract::{Path, State},
    http::StatusCode,
    Json, Router,
};
use serde::{Deserialize, Serialize};
use std::time::Instant;
use tracing::info;
use uuid::Uuid;

use crate::{models::ExportRequest, AppState};

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/", axum::routing::post(export_scene))
}

/// Export a NeRF scene to 3D format
pub async fn export_scene(
    State(state): State<AppState>,
    Json(request): Json<ExportRequest>,
) -> Result<Json<crate::models::ExportResponse>, AppError> {
    let start = Instant::now();

    // Verify scene exists
    let scene = sqlx::query_as::<_, crate::models::Scene>(
        "SELECT * FROM scenes WHERE id = ?",
    )
    .bind(request.scene_id)
    .fetch_optional(&state.db)
    .await?;

    if scene.is_none() {
        return Err(AppError::NotFound("Scene not found"));
    }

    // Generate export filename
    let export_id = Uuid::new_v4();
    let extension = match request.format {
        crate::models::ExportFormat::Obj => "obj",
        crate::models::ExportFormat::Gltf => "gltf",
        crate::models::ExportFormat::Glb => "glb",
        crate::models::ExportFormat::Ply => "ply",
    };

    let filename = format!("scene_{}.{}", export_id, extension);
    let file_path = state.uploads_dir.join(&filename);

    // Generate placeholder 3D data (in production, this would extract mesh from NeRF)
    let content = generate_placeholder_export(&request.format, request.include_textures);
    
    std::fs::write(&file_path, &content)
        .map_err(|e| AppError::Internal(format!("Failed to write export: {}", e)))?;

    let file_size = content.len() as u64;
    let export_time = start.elapsed();

    info!(
        "Exported scene {} to {} format in {:?}",
        request.scene_id, request.format, export_time
    );

    Ok(Json(crate::models::ExportResponse {
        scene_id: request.scene_id,
        format: request.format,
        file_url: format!("/api/v1/export/download/{}", export_id),
        file_size_bytes: Some(file_size),
        expires_at: None, // Permanent in this implementation
    }))
}

/// Download an exported file
pub async fn download(
    State(state): State<AppState>,
    Path(export_id): Path<Uuid>,
) -> Result<(StatusCode, Vec<u8>), AppError> {
    let patterns = ["obj", "gltf", "glb", "ply"];
    
    for ext in &patterns {
        let filename = format!("scene_{}.{}", export_id, ext);
        let file_path = state.uploads_dir.join(&filename);

        if file_path.exists() {
            let data = std::fs::read(&file_path)
                .map_err(|_| AppError::NotFound("Export not found"))?;
            return Ok((StatusCode::OK, data));
        }
    }

    Err(AppError::NotFound("Export not found"))
}

/// Generate placeholder 3D export content
fn generate_placeholder_export(format: &crate::models::ExportFormat, _include_textures: bool) -> Vec<u8> {
    match format {
        crate::models::ExportFormat::Obj => generate_obj(),
        crate::models::ExportFormat::Gltf => generate_gltf(),
        crate::models::ExportFormat::Glb => generate_glb(),
        crate::models::ExportFormat::Ply => generate_ply(),
    }
}

fn generate_obj() -> Vec<u8> {
    let content = r#"# NeRF Studio Export
# Generated by nerf-studio

v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 1.0 1.0 0.0
v 0.0 1.0 0.0

vn 0.0 0.0 1.0

f 1//1 2//1 3//1
f 1//1 3//1 4//1
"#;
    content.as_bytes().to_vec()
}

fn generate_gltf() -> Vec<u8> {
    let content = r#"{
  "asset": {"version": "2.0", "generator": "nerf-studio"},
  "scenes": [{"nodes": [0]}],
  "scene": 0,
  "nodes": [{"mesh": 0}],
  "meshes": [{
    "primitives": [{
      "attributes": {"POSITION": 0},
      "indices": 1
    }]
  }],
  "accessors": [
    {"bufferView": 0, "componentType": 5126, "count": 4, "type": "VEC3"},
    {"bufferView": 1, "componentType": 5123, "count": 6, "type": "SCALAR"}
  ],
  "bufferViews": [
    {"buffer": 0, "byteOffset": 0, "byteLength": 48},
    {"buffer": 0, "byteOffset": 48, "byteLength": 12}
  ],
  "buffers": [{"byteLength": 60}]
}"#;
    content.as_bytes().to_vec()
}

fn generate_glb() -> Vec<u8> {
    // Minimal GLB header + JSON chunk
    let json = r#"{"asset":{"version":"2.0"},"scene":0}"#;
    let mut glb = Vec::new();
    
    // GLB magic number
    glb.extend_from_slice(&[0x46, 0x54, 0x53, 0x67]); // 'g' 'l' 'T' 'F'
    // Version 2
    glb.extend_from_slice(&[0x02, 0x00, 0x00, 0x00]);
    // Total length (placeholder)
    glb.extend_from_slice(&[0x00; 4]);
    
    // JSON chunk
    let json_len = json.len() as u32;
    glb.extend_from_slice(&(json_len).to_le_bytes());
    glb.extend_from_slice(b"JSON");
    glb.extend_from_slice(json.as_bytes());
    
    glb
}

fn generate_ply() -> Vec<u8> {
    let content = r#"ply
format ascii 1.0
comment Generated by nerf-studio
element vertex 4
property float x
property float y
property float z
end_header
0.0 0.0 0.0
1.0 0.0 0.0
1.0 1.0 0.0
0.0 1.0 0.0
"#;
    content.as_bytes().to_vec()
}

/// Custom error type
#[derive(Debug)]
pub enum AppError {
    Database(sqlx::Error),
    NotFound(&'static str),
    Internal(String),
}

impl From<sqlx::Error> for AppError {
    fn from(err: sqlx::Error) -> Self {
        AppError::Database(err)
    }
}

impl axum::response::IntoResponse for AppError {
    fn into_response(self) -> axum::response::Response {
        match self {
            AppError::Database(e) => {
                tracing::warn!("Database error: {}", e);
                (StatusCode::INTERNAL_SERVER_ERROR, "Database error").into_response()
            }
            AppError::NotFound(msg) => {
                (StatusCode::NOT_FOUND, msg).into_response()
            }
            AppError::Internal(msg) => {
                tracing::warn!("Internal error: {}", msg);
                (StatusCode::INTERNAL_SERVER_ERROR, msg).into_response()
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_obj_generation() {
        let obj = generate_obj();
        let content = String::from_utf8_lossy(&obj);
        
        assert!(content.contains("v "));
        assert!(content.contains("f "));
        assert!(content.contains("NeRF Studio Export"));
    }

    #[test]
    fn test_gltf_generation() {
        let gltf = generate_gltf();
        let content: serde_json::Value = serde_json::from_slice(&gltf).unwrap();
        
        assert_eq!(content["asset"]["version"], "2.0");
        assert!(content["scenes"].is_array());
    }

    #[test]
    fn test_ply_generation() {
        let ply = generate_ply();
        let content = String::from_utf8_lossy(&ply);
        
        assert!(content.starts_with("ply"));
        assert!(content.contains("element vertex"));
    }
}
